version: "3"

services:
  postgres:
    image: postgres
#    restart: always
    ports:
      - "6432:5432"
    env_file:
      - ./env/pg_dev.env
    volumes:
      - pgdata:${PGDATA_PATH}
    environment:
      PGDATA: ${PGDATA_PATH}


volumes:
  pgdata:
