"""empty message

Revision ID: 1646cdb5353d
Revises: 
Create Date: 2023-03-14 16:18:53.269170

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1646cdb5353d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_room',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_started', sa.Boolean(), nullable=False),
                    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_game_room_id'), 'game_room', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hash_password', sa.String(), nullable=False),
                    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('game_player',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_game_player_id'), 'game_player', ['id'], unique=False)
    op.create_table('game_piece',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('player_id', sa.Integer(), nullable=False),
                    sa.Column('x', sa.Integer(), nullable=False),
                    sa.Column('y', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['player_id'], ['game_player.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_game_piece_id'), 'game_piece', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_piece_id'), table_name='game_piece')
    op.drop_table('game_piece')
    op.drop_index(op.f('ix_game_player_id'), table_name='game_player')
    op.drop_table('game_player')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_game_room_id'), table_name='game_room')
    op.drop_table('game_room')
    # ### end Alembic commands ###
