"""empty message

Revision ID: ee3f60287508
Revises: f7a824d463c2
Create Date: 2023-03-20 20:36:36.025367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3f60287508'
down_revision = 'f7a824d463c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_room', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_room', 'name')
    # ### end Alembic commands ###
