"""empty message

Revision ID: f7a824d463c2
Revises: d4be7c1b2059
Create Date: 2023-03-19 15:48:49.002212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a824d463c2'
down_revision = 'd4be7c1b2059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_piece', sa.Column('player_id', sa.Integer(), nullable=False))
    op.drop_constraint('game_piece_user_id_fkey', 'game_piece', type_='foreignkey')
    op.create_foreign_key(None, 'game_piece', 'game_player', ['player_id'], ['id'])
    op.drop_column('game_piece', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_piece', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game_piece', type_='foreignkey')
    op.create_foreign_key('game_piece_user_id_fkey', 'game_piece', 'users', ['user_id'], ['id'])
    op.drop_column('game_piece', 'player_id')
    # ### end Alembic commands ###
